---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sakuma.
--- DateTime: 11/23/19 11:39 PM
---

maxint=10
for i = 0,maxint do
    if (i < maxint/2) then
        r=i*2
        g=i*2
        b=maxint
    else
        r=maxint
        g=2*(maxint-i)
        b=2*(maxint-i)
    end

    print(math.floor(r*225/maxint),math.floor(g*255/maxint),math.floor(b*225/maxint))
    --print(math.floor(r*225/maxint),2*math.floor(255*g/maxint),math.floor(b*225/maxint))
end