---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sakuma.
--- DateTime: 11/23/19 8:51 PM
---

--[[
 You can add a small description to the macro here (This is optional)
]]
function main ()
    Command_Notification("Hello world, from IDE");
    return "SUCCESS";
end;
